language: csharp
mono: none
dotnet: 2.1
script:
- dotnet publish Runit.Backend/ -c Release -o $TRAVIS_BUILD_DIR/publish
install:
- echo 'rancor.mortimer.nu ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNTuni9lck7RnBoGNyh1hdJmUn3BauxnKYpYgaXweF7HA2zq4t56AS1CqjMWpXpBL2MyI4i6pdUge2KYApbJGIs=' >> $HOME/.ssh/known_hosts
deploy:
- provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_d4327513f1db_key -iv $encrypted_d4327513f1db_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
